# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-08 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenreImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_id', models.IntegerField()),
                ('new_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenreLabelImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_id', models.IntegerField()),
                ('new_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
