# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_id', models.IntegerField()),
                ('new_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
