# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
