# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_auto_20170624_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='media',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='albums.MediaType'),
            preserve_default=False,
        ),
    ]
