# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_auto_20170624_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='1987-10-14 00:14'),
            preserve_default=False,
        ),
    ]
