# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-08 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_album_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='album',
            name='label',
        ),
        migrations.AddField(
            model_name='album',
            name='labels',
            field=models.ManyToManyField(to='albums.RecordLabel'),
        ),
    ]
