# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-08 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_left', models.CharField(max_length=6)),
                ('color_right', models.CharField(max_length=6)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='albums.Genre')),
            ],
        ),
    ]
