# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_auto_20170624_1609'),
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='albums.Album')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.Location')),
            ],
        ),
    ]
